### ISSUE TITLE
Allow instantiating multiple instances

### ISSUE THREAD

**Issue by oleg-codaio** [jwrw/ESP_EEPROM#10]
The current implementation of this class deliberately hides the `EEPROMClass` constructor that takes in a specific sector, with the sector being hardcoded as:

```c
((uint32_t)&_EEPROM_start - 0x40200000) / SPI_FLASH_SEC_SIZE
```

While this specific sector is reserved for EEPROM emulation via flash memory, as far as I can tell there are other sectors that can be safely used, in which case having multiple instances of this library can be useful.

For my specific use case, I need to store some large certificates to flash (~3KB) as well as some other state. Storing this data in the same sector defeats the purpose of this library since the sector needs to be erased each time. However, I've had success using the next sector after the default, as well as instantiating two instances of this class (I'm also using `#define NO_GLOBAL_EEPROM`). I didn't notice any unpredictability as this comment describes:

https://github.com/jwrw/ESP_EEPROM/blob/33a9d4f64ff1ff1d4a9a67196e32b91dc9a80a7b/src/ESP_EEPROM.cpp#L128-L130

As a start, the constructor with the sector could be promoted to public visibility. To make it easier to use, another approach could be to have a constructor with a sector offset, which would avoid having to hardcode the address above in user code.

**Comment by jwrw** [comment]
Saying 'unpredictable' really means I was too lazy to think of and document all the problems that might happen but in practice there shouldn't be a problem.  This library was meant to be as simple as possible to use and so I went with the usual Arduino practice of creating the EEPROM instance for the user.
There is already a second public constructor that allows you to specify the sector to use.

**Comment by vaskevich** [comment]
> There is already a second public constructor that allows you to specify the sector to use.

I do see this constructor but it currently isn't public:

https://github.com/jwrw/ESP_EEPROM/blob/09214cb795d55e9366d87a20663c0124f6d95b2f/src/ESP_EEPROM.h#L111-L112

**Comment by jwrw** [comment]
Quite right - missed that! Now fixed.

**Comment by vaskevich** [comment]
Awesome, thanks!
