### ISSUE TITLE
Port to ESP32?

### ISSUE THREAD

**Issue by RobotZwrrl** [jwrw/ESP_EEPROM#11]
Hi there,

Trying to make this library work on an ESP32 and running in to the issue. Here is the error:

`/Users/myusername/Documents/Arduino/libraries/ESP_EEPROM/src/ESP_EEPROM.cpp:90:21: fatal error: c_types.h: No such file or directory`

If it helps, the ESP32 I'm specifically using in the Boards menu is "ESP32 Wrover Module".

Has the library been tested with ESP32? Any known ways to fix this error or port the library?

Thank you

**Comment by jie326513988** [comment]
Has it been solved

**Comment by aahmed7** [comment]
You should use preferences library for esp32 instead of this. 

<https://github.com/espressif/arduino-esp32/tree/master/libraries/Preferences>

**Comment by jwrw** [comment]
As noted by @aahmed7 this isn't really needed on ESP32 so I've not tried a port and wouldn't intend to.  You could use the technique for writing to an EEPROM sector but I think quite a lot would need to change to make it work reliably on the ESP32 due to the different layout.
