### ISSUE TITLE
What is the state of the data if a loss of power occurs during a commit?

### ISSUE THREAD

**Issue by Llaves** [jwrw/ESP_EEPROM#13]
Will the index still point to the last written data, or will it point to incompletely written data?
Presumably if the crash occurs during an erase, you will be in some indeterminate state.
In either case, is it possible to determine that the data is invalid?

**Comment by jwrw** [comment]
If the crash is during an erase then all bets are off - your data is almost certainly gone! The library stores and uses the size of your parameter structure as a kind of magic number to determine if the EEPROM has valid data.  When you next try to use the library it will probably detect the missing/corrupt size information and re-initialise the EEPROM area.

If the crash occurs during data write part of the commit, you should still be OK as the bitmap is only updated after the new data is written.  When the device restarts, it will use the bitmap to determine the last data written - which will be the version in place before the crash.
