### ISSUE TITLE
VSCode incompatibility

### ISSUE THREAD

**Issue by Llaves** [jwrw/ESP_EEPROM#14]
Not an issue with this library - just a warning to others:
If you try to run the examples from VSCode using the VSCode serial monitor you will get no output, which might leave you wondering what's wrong with the code. It's not the code, it's the serial monitor. There's something going on with the monitor that is breaking output in certain conditions. Use a different monitor/terminal emulator.

**Comment by jwrw** [comment]
Thanks for the note - it's probably some issue with the baud rate settings.  The 8266 starts at some weird baud setting which then might get changed by your sketch.  YMMV
