### ISSUE TITLE
put() versus write() and get() versus read()

### ISSUE THREAD

**Issue by johnmcv** [jwrw/ESP_EEPROM#16]
Sorry to ask a (perhaps) stupid question.  I see the keywords include write and read, but the examples use put and get.  Can someone please clarify which to use and when?

Thank you,
John

**Comment by jwrw** [comment]
You've probably solved this by now but there is documentation for each in the doc folder - open up doc/html/index.html and follow the links.

`read`/`write`  access/set a single byte at a specified position in your buffer of data you are using.

`get`/`put` are more friendly in that they write an entire variable or struct to the specified position in the buffer - they work out how many bytes are read or written.

All of these just interact with the buffer held in the library - the buffer only goes to EEPROM when you `commit()`

`put` and `get` should really be in the keywords

**Comment by johnmcv** [comment]
Jim,
I had not solved the issue already, so I really appreciate your help.
Thank you!

John
