### ISSUE TITLE
Example ESP_EEPROM_Use does not function as expected.

### ISSUE THREAD

**Issue by mouridis** [jwrw/ESP_EEPROM#2]
Flashing the example "as-is" in a brand new Wemos D1 mini Pro gives the following output:

![esp_eeprom_bug](https://user-images.githubusercontent.com/33179613/38600474-cf83e644-3d96-11e8-8d54-8294805ef005.jpg)

**Comment by jwrw** [comment]
Fixed in V2.0.0
