### ISSUE TITLE
ESP_EEPROM_Wipe systematic compilation error

### ISSUE THREAD

**Issue by regpa** [jwrw/ESP_EEPROM#4]
1/ I have installed the Arduino IDE on a Raspbian distrbution on a PI3B+.
2/ I have added the ESP8266 library
3/ I have added the EE_EEPROM library
when I compile the example ESP_EEPROM_Wipe I systematically get this error:

`/home/pi/arduino-nightly/libraries/ESP_EEPROM/src/ESP_EEPROM.cpp:90:21: fatal error: c_types.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board Arduino/Genuino Uno.`

the missing file is under the `/home/pi/.arduino15` folder tree

note: the native arduino examples are working fine

could you please give me some light ?

**Comment by per1234** [comment]
> `Error compiling for board Arduino/Genuino Uno`

This library is for ESP8266. You're compiling it for the Uno, which is not ESP8266. If you're not using an ESP8266 then you can't use this library. If you are using an ESP8266 then you need to select the correct board from the **Tools > Board** menu.
