### ISSUE TITLE
commit() should not report error if data not changed

### ISSUE THREAD

**Issue by buteomont** [jwrw/ESP_EEPROM#5]
It seems that if _commit()_ is called, and the data in the internal buffer has not changed since the last commit, then _commit()_ reports an error (returns false).  Thus we have no way of determining that the error is caused by bad data, bad flash memory, or that the data simply did not change.    

It seems that a better idea would be to always return _true_ from a commit, as long as the data in the buffer is identical to the data in EEPROM.  As a programmer and a user, I don't really care if the commit was aborted because the data was changed, only if it failed because of an error.

**Comment by raichea** [comment]
I've recently starting using this library and ran into this issue. I've created a pull request for changes that cause a true return if the data hasn't changed.
