### ISSUE TITLE
ESP_EEPROM-master not compiling with LOLIN32 or WEMOS LOLIN32

### ISSUE THREAD

**Issue by peteDDD** [jwrw/ESP_EEPROM#6]
Sorry if this is an easy fix but I already have half a day in trying to figure out how to get the ESP_EEPROM library to compile for my ESP32 boards:  LOLIN32 or WEMOS LONLIN32

I have downloaded V2 via zip and installed them, removing other ESP_EEPROM libraries from my system.  

This is the compile-time error I get:

C:\Users\Pete\Documents\Arduino\libraries\ESP_EEPROM-master\src\ESP_EEPROM.cpp:90:21: fatal error: c_types.h: No such file or directory

compilation terminated.
 
the file ESP_EEPROM.cpp is definitely in this directory and it is a good file.

suggestions are appreciated.  stuck until I solve this.
Thanks!

**Comment by Gizmodo** [comment]
c_types.h is part of https://github.com/esp8266/Arduino
Did you install it?

**Comment by jwrw** [comment]
It could probably be made to work on the ESP32 but this library is really for the ESP8266 family.
