### ISSUE TITLE
 Doubt about flash memory operation

### ISSUE THREAD

**Issue by jorgele** [jwrw/ESP_EEPROM#9]
Hi.
I have read that only around 10,000 write cycles are guaranteed for flash memory, although it can be much more. But this question arises: if using this library I write 10,000 times in a sector, would only that sector be damaged, or the entire memory? Because I need to register a variable around 100000 times without risk, and I must do it because where I am going to use my system, the power supply is unpredictable, and, if there is a power outage, I need to be sure what the last value of the variable once the system restarts. I think that I could change the sector every time I approach the limit of 10,000 writes, but I don't know if that would solve this problem. I appreciate your help.

**Comment by jwrw** [comment]
A rather late reply but...
The 10,000 figure is probably either erase cycles or writes to a single cell (bit).  The whole point of this library is to spread out the writes so if you have only a small amount of data it is written to a different area in the sector each time it is changed.  The sector is only flashed when there are no more areas left that we can write to.  So, as a rough example, if your data is about 1/10 the size of the sector, then the sector only needs to be flashed once in every 10 commits.  Similarly, the actual writes are spread across the sector, so an individual memory cell is only written to at most just once every 10 commits.
A failure is likely to affect only individual cells so moving to a new sector might help you.  You would probably also want to consider some kind of checksum if your data is critical and you are expecting to run up to the guaranteed limit in this way.
